---
name: Manual release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-binary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build Go binary
        run: |
          cd gysmo
          go build -o binary_test
          chmod +x binary_test
          ./binary_test

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          VERSION=$(cat VERSION)
          gh release create "v$VERSION" \\
              --repo="$GITHUB_REPOSITORY" \\
              --title="$VERSION" \\
              --generate-notes \\
              gysmo
