---
name: Build and create release

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build Go binary
        run: |
          go build -o gysmo

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(cat VERSION)
          gh release create "v$VERSION" \\
              --repo="$GITHUB_REPOSITORY" \\
              --title="$VERSION" \\
              --generate-notes \\
              gysmo

      - name: Clean up
        run: |
          rm gysmo
