name: Validate versioning

on:
  pull_request:
    branches:
      - rc
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Validate version consistency
        run: ./check_versions.sh
